# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.

USE="bluetooth wayland dist-kernel elogind -systemd opengl nvenc lua v4l dbus screencast alsa"
ACCEPT_LICENSE="-* @FREE @BINARY-REDISTRIBUTABLE"

COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
MAKEOPTS="-j28 -l32"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="http://mirror.mephi.ru/gentoo-distfiles/ \
    ftp://mirror.mephi.ru/gentoo-distfiles/ \
    rsync://mirror.mephi.ru/gentoo-distfiles/ \
    https://mirror.yandex.ru/gentoo-distfiles/ \
    http://mirror.yandex.ru/gentoo-distfiles/ \
    ftp://mirror.yandex.ru/gentoo-distfiles/"
