# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.

USE="-gtk -gnome dist-kernel dbus alsa wayland bluetooth opengl nvenc cuda lua v4l screencast"

# COMMON_FLAGS="-march=native -O2 -pipe"
COMMON_FLAGS="-march=alderlake -mabm -mno-kl -mno-pconfig -mno-sgx -mno-widekl -mshstk --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=36864 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# PYTHON_TARGETS='python3_13'
# PYTHON_SINGLE_TARGET='python3_13'

RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
MAKEOPTS="-j16 -l32"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="http://mirror.mephi.ru/gentoo-distfiles/ \
    ftp://mirror.mephi.ru/gentoo-distfiles/ \
    rsync://mirror.mephi.ru/gentoo-distfiles/ \
    https://mirror.yandex.ru/gentoo-distfiles/ \
    http://mirror.yandex.ru/gentoo-distfiles/ \
    ftp://mirror.yandex.ru/gentoo-distfiles/"
