# created by eselect-repo

[gentoo-zh]
location = /var/db/repos/gentoo-zh
sync-type = git
# sync-uri = https://github.com/microcai/gentoo-zh.git
sync-uri = https://github.com/gentoo-zh/overlay.git
auto-sync = yes

[hyproverlay]
location = /var/db/repos/hyproverlay
sync-type = git
sync-uri = https://codeberg.org/hyproverlay/hyproverlay.git
auto-sync = yes

[bentoo]
location = /var/db/repos/bentoo
sync-type = git
sync-uri = https://github.com/lucascouts/bentoo.git
auto-sync = yes
